// Called automatically by the npm "version" lifecycle hook.
// Reads the new version from package.json and writes js/version.js.
const fs   = require('fs');
const path = require('path');

const pkg     = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));
const version = pkg.version;

const content =
    `// Auto-generated by scripts/update-version.js — do not edit manually.\n` +
    `// Run \`npm version patch|minor|major\` to bump.\n` +
    `export const APP_VERSION = '${version}';\n`;

fs.writeFileSync(path.join(__dirname, '..', 'js', 'version.js'), content, 'utf8');
console.log(`[update-version] js/version.js → v${version}`);
